Bugfix/1011 gq ignore warmup draws
stan-dev/cmdstan pull request #1017
Opened 2021-05-16 18:52 UTC by mitzimorris

#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Standalone generated quantities will use all draws present in a sample, including warmup draws.

#### Intended Effect:

1. Allow users to use warmup draws as well as sampling draws.  by default, warmup draws aren't written to the output.

2. Simplify both interface and computation - CmdStan doesn't need to compute which rows of the sample are to be used by standalone generated quantities service, it just passes along the entire sample.  else, will need to reason about num_warmup, num_samples, and thin when calling the services layer in addition to adding logic to the interface to give user control over whether to not to use warmup draws.   Wrapper interfaces can implement additional logic to add this functionality, if needed.

#### How to Verify:

Unit tests

#### Side Effects:

N/A

#### Documentation:

Will document in online docs.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):   Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2021-05-16 19:37 UTC, funko-unko commented
Nice, thanks!

2021-05-17 07:07 UTC, rok-cesnovar requested changes

2021-05-17 07:07 UTC, rok-cesnovar commented on src/cmdstan/command.hpp
> +    size_t num_rows = fitted_params.samples.rows();  // this is the fix
```suggestion
    size_t num_rows = fitted_params.samples.rows();
```
Remove comment.

2021-05-17 14:32 UTC, rok-cesnovar approved these changes

2021-05-17 14:32 UTC, merged